### ISSUE TITLE
Auto init child objects?

### ISSUE THREAD

**Issue by varffs** [interglobalvision/globie-wordpress-starter-pack#103]
I wonder if we can auto trigger the `init()` function on child objects of the `Site` object? Or if the Site object should have an autoloader function with a ignore whitelist for child objects we want to init after doc ready for example?

If we did auto `init` everything then all the conditional logic would go in each child object init rather than in the generally rubbish init of the Site object.

Or should we find a better way in general rather than this objects pattern we are currently using?

**Comment by mixcas** [comment]
IMO the criteria should be:

- `Site.init()` is in charge of checking if other parts should be or not initialized
- `Site.Foo.init()` is in charge checking if required properties are available

Eg.

- `Site.Foo` depends on an request response to run or not, this is checked at `Site.init()`
- `Site.Foo` requires certain DOM elements to exist to actually work, this is checked at `Site.Foo.init()`


This way `Site` checks on every run what needs to be initialized, on every run and even on other events like resize. `Site.Foo` is only concerned with the properties it need to work being available, like DOM elements or library objects like `Swiper`.

```
Site.init = function() {
// [...]
  if(response) {
    Site.Foo.init()
  }
}
Site.Foo.init = function() {
// [...]
  if($('.bar').length) {
    this.bar();
  }
}
```

**Comment by varffs** [comment]
You what you are saying is all the checks run inside `Site.init()` for the child objects? That is fine by me but would be nice to have a convention.

**Comment by mikeyrayvon** [comment]
the issue doesnt apply to the new structure. going to close
