### ISSUE TITLE
typos font-sizes()

### ISSUE THREAD

**Issue by mikeyrayvon** [interglobalvision/globie-wordpress-starter-pack#114]
on lines 131 & 155 of site.styl

reads `font-size(...` should be `font-sizes(...`

**Comment by varffs** [comment]
Not trying to be annoying but I think a hotfix commit to master for stuff like this is fine without even creating an issue first. This also seems like a high priority fix

**Comment by mikeyrayvon** [comment]
youre being fucking annoying

**Comment by varffs** [comment]
fixed in #a27bda7f79b37776f09e805ff9eca47f886cf878
