### ISSUE TITLE
refactor jquery dependency

### ISSUE THREAD

**Issue by varffs** [interglobalvision/globie-wordpress-starter-pack#117]
I think we should move from the jquery cdn lib loading before the rest of our js to just one build js file including everything. For this we should install jquery as a bower dep as well as reworking the gulpfile to build into one final file. This could be 2 feature branches

We would be reducing requests to 3 small files to 1 request for a still small file. This should be a perf improvement. It would also avoid any Bower dep issues when libs declare jquery as a requirement. It also improve offline development not needing to wait for timeout for the fallback. It also will reduce the size of the starterpack. It will also allow us to keep up to date with jquery versions with a lot less work

**Comment by mixcas** [comment]
What made you change your mind? You were all about CDN before.

**Comment by varffs** [comment]
The trigger was locally developing with a wobbly connection and the page hanging on the CDN request before the javascript would run. But I've been thinking about 1 js file for a while

**Comment by mixcas** [comment]
I stated that same issue before more than once, specially when we were working in Aeromoto. I got ignored cuz blah blah blah. 

Anyway, the internet thinks CDN is better.

**Comment by varffs** [comment]
People change their minds.

Sources?

**Comment by mixcas** [comment]
Really any result on google from the last 2 years. The only real issue is chinese users.

It's really not about opinions. CDN works better for delivering content, the advantage of parallel downloads, optimized caching settings and that the user might have it cached already. 

> We would be reducing requests to 3 small files to 1 request for a still small file.

Merging lib+main sounds good for *production*, I'm up for that. So we have 2 requests in parallel, one for jquery to the cdn and to our site js file.

> It would also avoid any Bower dep issues when libs declare jquery as a requirement.

Example?

> It also will reduce the size of the starterpack. It will also allow us to keep up to date with jquery versions with a lot less work

how?

**Comment by varffs** [comment]
>CDN works better for delivering content, the advantage of parallel downloads, optimized caching settings and that the user might have it cached already.

All true, but it is a second request that could be removed totally. We will always have to make a same domain request to at least 1 js file

>Bower dep issues: Example?

We don't have any override by default in our bower.json. So I think anything listing jQuery as a dep might be getting it installed? As another version. I haven't checked but the point is using a package manager there are dependencies managed and currently we don't know if we could run into issues here

>allow us to keep up to date with jquery versions with a lot less work: how?

Currently to upgrade jQuery version (each version is generally smaller and faster) we have to download the file from CDN, replace the local fallback file, upgrade the references in the footer.php. Using Bower we just install jquery at latest each time. I've done this a few times and it is boring and a bad update practice
