### ISSUE TITLE
add text-columns to grid mixin

### ISSUE THREAD

**Issue by mikeyrayvon** [interglobalvision/globie-wordpress-starter-pack#120]
add `.text-columns-` lines. *see `if $gutter` and `for col in...`

```
// GRID

grid($width = false, $gutter = false, $size = false, $cols = 12)

  if $width
    .container
      width: $width

  if $gutter
    .grid-item
      padding: 0 ( $gutter / 2 )
    .text-columns
      column-gap: $gutter

  // COLUMN SIZES & OFFSETS, TEXT COLUMNS

  if $gutter and $size
    for offset in 0..($cols - 1)
      .grid-row
        .offset-{$size}-{offset}
          margin-left: ( 100% / $cols ) * offset

    for col in 1..$cols
      .item-{$size}-{col}
        flex-basis: ( 100% / $cols ) * col
      .grid-row > .item-{$size}-{col}
        max-width: ( 100% / $cols ) * col
      .grid-column > .item-{$size}-{col}
        max-height: ( 100% / $cols ) * col
      .text-columns-{$size}-{col}
        column-count: col
```

**Comment by varffs** [comment]
I dont' really understand what these are? Matching text col things that work inside grid items, or replace grid items?

**Comment by mikeyrayvon** [comment]
its just for columnized text. so we can have a item-12 with 2 6-width columns of text, with a gap that matches the grid gutter.

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns/Using_multi-column_layouts

**Comment by mikeyrayvon** [comment]
its just for columnized text. so we can have a item-12 with 2 6-width columns of text, with a gap that matches the grid gutter.

```
<div class="grid-item item-s-12">
  <p class="text-columns text-columns-s-2">
    This text will be split into two columns, each the width of an .item-s-6, with our grid gutter between them.
  </p>
</div>
```

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Columns/Using_multi-column_layouts

**Comment by varffs** [comment]
Looks good. My only issue really is that `.text-columns-{$size}-{col}` is going to generate markup almost never to be used like `.text-columns-s-12`. Not sure I can think of an obvious good solution there but does mean we will be generated css we dont need. (Would love something to clean the css after builds but that never seems to be made)

**Comment by mikeyrayvon** [comment]
yea just make another loop for the text cols that only goes to 4

or make a condition in the loop to check what col number were on before generating the text-columns-size- class
