### ISSUE TITLE
Move on from Bower

### ISSUE THREAD

**Issue by varffs** [interglobalvision/globie-wordpress-starter-pack#132]
We need a new javascript dependency management approach as Bower is no longer cool (probably because it was too stable and easy to use).

Will this be part of a totally new build system? Or will we work out another approach for our Gulp build system?

**Comment by mixcas** [comment]
full webpack please

**Comment by varffs** [comment]
do the research. lets do that change

**Comment by mikeyrayvon** [comment]
we've moved on, now we need to remove bower config files

**Comment by varffs** [comment]
we haven't yet I don't think. Is there a way to install front end js modules with our webpack build?

**Comment by mikeyrayvon** [comment]
yea with yarn/npm

**Comment by mixcas** [comment]
Yeah, we are not supporting bower anymore since this version, the bower file should be deleted.
