### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by varffs** [interglobalvision/globie-wordpress-starter-pack#65]

**Comment by varffs** [comment]
Maybe just as simple as `IGVWP`

**Comment by varffs** [comment]
Or something more weird?

**Comment by varffs** [comment]
`globie-wordpress-zone`

**Comment by mixcas** [comment]
lets DO IT
`globie-chill-boilerplate`

**Comment by varffs** [comment]
`igv-wp-jasmine`

**Comment by varffs** [comment]
`globies-opinionated-wordpress-starter-theme`

**Comment by varffs** [comment]
`boil`

**Comment by mikeyrayvon** [comment]
`igv-wp-boil`

**Comment by mikeyrayvon** [comment]
`globie-wp-starter-pack`

**Comment by mixcas** [comment]
`globie-socially-responsible-starter-pack`

**Comment by mixcas** [comment]
`globie-im-a-web-dev-starter-pack`

**Comment by mikeyrayvon** [comment]
`globie-starter`

**Comment by mikeyrayvon** [comment]
`globie-starter-pack`

**Comment by mikeyrayvon** [comment]
`igv-wp-boil`
