### ISSUE TITLE
git clone with depth=1

### ISSUE THREAD

**Issue by mixcas** [interglobalvision/globie-wordpress-starter-pack#78]
I think we should keep doing `--depth=1` while cloning the repo, as in:
`git clone git@github.com:interglobalvision/globie-wordpress-starter-pack.git --depth=1`
to avoid having repos with ~220 commits from boilerplate

this only requires to update README.md

**Comment by mikeyrayvon** [comment]
i concur

**Comment by varffs** [comment]
I think this is incomplete. If our setup instructions are to clone then rename remotes etc then yh that makes sense. But that isn't needed for any of this to work and is a pattern I don't use. (I clone for latest and move the files into a cloned empty repo for whatever project).

So either have the full instructions and explain them as option. Or remove the git clone example completely

**Comment by mixcas** [comment]
i think this is where the setup script is handy
so u clone and run the script and u have a brand new shiny wp theme with proper theme name, proper repo name and stuff. no?

**Comment by varffs** [comment]
yh def. but when you setup from this repo do you actually rename the git repo and change its remotes?

**Comment by mixcas** [comment]
im close this for now
