### ISSUE TITLE
styl lint "sortOrder": "alphabetical" its annoying

### ISSUE THREAD

**Issue by mixcas** [interglobalvision/globie-wordpress-starter-pack#94]
This outputs a lot of warnings.

`sortOrder warning prefer custom grouped when sorting properties`

 I think it should be set to false. I find it annoying to have to worry about the order we declare our properties in stylus.

**Comment by varffs** [comment]
Bullshit. Only annoying if you get it wrong. Once you learn the order [which is reasonably logical] it will just be a reminder to keep copy tidy and clean.
