### ISSUE TITLE
dont assign font-sizes to headings

### ISSUE THREAD

**Issue by mikeyrayvon** [interglobalvision/globie-wordpress-starter-pack#95]
and change font-size classes to match margin/padding classes:

```
.font-size-small
.font-size-basic
.font-size-mid
.font-size-large
```

something like this

**Comment by mikeyrayvon** [comment]
font-sizing of heading elements hardly ever corresponds to hierarchy. we should not be confusing semantics with style

**Comment by varffs** [comment]
yeah i like this idea

**Comment by mikeyrayvon** [comment]
im already doing it on lanza and ketvoid and it works better
